version: 2
jobs:
  test:
    working_directory: ~/knex-cleaner
    docker:
      - image: cimg/node:14.21

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v14-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-v14-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test --ci --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: ./reports/
workflows:
  version: 2
  test:
    jobs:
      - test
